import { NextResponse } from 'next/server';
import { getAuth } from '@/lib/auth';
import { SignJWT } from 'jose';

export const dynamic = 'force-dynamic';

export async function GET() {
    try {
        const session = await getAuth();
        if (!session || (session.role !== 'ADMIN' && session.role !== 'EXECUTIVE')) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const secret = new TextEncoder().encode(process.env.JWT_SECRET || 'super-secret-key-change-this-in-prod');

        // Create a short-lived token (15 seconds)
        // This token proves that it was generated by the Admin recently.
        const token = await new SignJWT({ type: 'OFFICE_QR' })
            .setProtectedHeader({ alg: 'HS256' })
            .setIssuedAt()
            .setExpirationTime('20s') // 20 seconds validity window
            .sign(secret);

        return NextResponse.json({ token });

    } catch (error) {
        return NextResponse.json({ error: "Internal Error" }, { status: 500 });
    }
}
