"use server";

import { signJWT, getAuth } from "@/lib/auth";
import { logInfo, logError } from "@/lib/log-utils";

export async function generateOfficeToken(lat?: number, lng?: number) {
    const session = await getAuth();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'EXECUTIVE')) {
        throw new Error("Unauthorized");
    }

    const payload = {
        type: 'OFFICE_QR',
        timestamp: Date.now(),
        location: (lat && lng) ? { lat, lng } : null
    };

    logInfo(`Office QR token generated by admin ${session.id}`, { location: payload.location });

    // Sign with 1 minute expiration to enforce rotation
    return await signJWT(payload, '1m');
}

export async function generateUserToken() {
    const session = await getAuth();
    if (!session) throw new Error("Unauthorized");

    const payload = {
        type: 'USER_QR',
        userId: session.id,
        timestamp: Date.now()
    };

    logInfo(`User QR token generated for ${session.id}`);

    // Sign with 15 minute expiration
    return await signJWT(payload, '15m');
}
